Fix error when stop() is called on certain conditions (#70)
Fixes:
  AttributeError: "'NoneType' object has no attribute 'join'"

when calling stop and not connected (invalid password, fs is not running)